// SPDX-License-Identifier: MIT
// Copyright (c) 2024 Dependency-Track Risk Dashboard contributors
'use strict';

// ── Environment configuration ─────────────────────────────────────────────────
// Single place where process.env is read and validated.  The boot sequence calls
// load() first and fails fast with an actionable message, so a misconfigured
// container never reaches the point of accepting requests (CLAUDE.md §6.1).
//
// parseConfig(env) is pure and takes the environment as a parameter so it can be
// unit-tested without mutating process.env.

const path = require('path');

// Q12: defaults live here rather than being scattered through the modules that
// consume them, so a reader can see the whole tuneable surface in one place.
const DEFAULTS = {
  PORT:                      '3001',
  LOG_FORMAT:                'text',
  CACHE_DIR:                 '/data',
  ENV_FILE:                  '/app/.env',
  CACHE_TTL_HOURS:           '24',
  REPORT_CONCURRENCY:        '5',
  VIOLATION_CONCURRENCY:     '3',
  POSTGRES_HOST:             'dt-postgres',
  POSTGRES_PORT:             '5432',
  POSTGRES_USER:             'dtdash',
  POSTGRES_DB:               'dtdash',
  SESSION_ABSOLUTE_HOURS:    '8',
  SESSION_IDLE_HOURS:        '2',
};

// Pool sizing and timeouts are fixed by the design (CLAUDE.md §5.2) rather than
// exposed as environment variables — they are tuned against the server's
// max_connections and changing one without the other is a footgun.
const POOL_MAX                       = 15;
const STATEMENT_TIMEOUT_MS           = 30_000;
const IDLE_IN_TRANSACTION_TIMEOUT_MS = 30_000;

class ConfigError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ConfigError';
    this.code = 'CONFIG_INVALID';
  }
}

/** Read a value, falling back to the documented default. */
function raw(env, key) {
  const v = env[key];
  return (v === undefined || v === null || v === '') ? DEFAULTS[key] : String(v);
}

/** Parse a positive integer, or throw a message naming the variable. */
function positiveInt(env, key, { min = 1, max = Number.MAX_SAFE_INTEGER } = {}) {
  const value = raw(env, key);
  const n = Number(value);
  if (!Number.isInteger(n) || n < min || n > max) {
    throw new ConfigError(
      `${key} must be an integer between ${min} and ${max} (received "${value}")`
    );
  }
  return n;
}

/** Parse a non-empty string, or throw. */
function requiredString(env, key, hint) {
  const value = raw(env, key);
  if (!value || !String(value).trim()) {
    throw new ConfigError(`${key} is required but was not set.${hint ? ` ${hint}` : ''}`);
  }
  return String(value).trim();
}

/**
 * Build the effective configuration from an environment object.
 * Pure — no process.env access, no I/O — so it is directly unit-testable.
 *
 * @param {object} env  typically process.env
 * @returns {object} frozen configuration
 * @throws {ConfigError} on any missing or malformed value
 */
function parseConfig(env) {
  const cacheDir = raw(env, 'CACHE_DIR');
  const logFormat = raw(env, 'LOG_FORMAT');
  if (logFormat !== 'text' && logFormat !== 'json') {
    throw new ConfigError(`LOG_FORMAT must be "text" or "json" (received "${logFormat}")`);
  }

  const cfg = {
    port:      positiveInt(env, 'PORT', { min: 1, max: 65535 }),
    logFormat,
    cacheDir,
    envFile:   raw(env, 'ENV_FILE'),

    // Paths derived once so no module recomputes them.
    paths: {
      cacheFile:   path.join(cacheDir, 'violation-cache.json'),
      cacheTmp:    path.join(cacheDir, 'violation-cache.tmp.json'),
      configFile:  path.join(cacheDir, 'app-config.json'),
      configTmp:   path.join(cacheDir, 'app-config.tmp.json'),
      schedDir:    path.join(cacheDir, 'scheduled-reports'),
      reportDir:   path.join(cacheDir, 'reports'),
      adminCreds:  path.join(cacheDir, 'admin-credentials.json'),
    },

    cacheTtlMs:           positiveInt(env, 'CACHE_TTL_HOURS', { min: 1, max: 8760 }) * 3_600_000,
    reportConcurrency:    positiveInt(env, 'REPORT_CONCURRENCY', { min: 1, max: 50 }),
    violationConcurrency: positiveInt(env, 'VIOLATION_CONCURRENCY', { min: 1, max: 50 }),

    // S1: session lifetimes are read here but not enforced until phase 2, so a
    // deployment can be configured ahead of the auth rollout without a restart.
    session: {
      absoluteHours: positiveInt(env, 'SESSION_ABSOLUTE_HOURS', { min: 1, max: 720 }),
      idleHours:     positiveInt(env, 'SESSION_IDLE_HOURS', { min: 1, max: 720 }),
    },

    db: {
      host:     raw(env, 'POSTGRES_HOST'),
      port:     positiveInt(env, 'POSTGRES_PORT', { min: 1, max: 65535 }),
      user:     raw(env, 'POSTGRES_USER'),
      database: raw(env, 'POSTGRES_DB'),
      password: requiredString(
        env, 'POSTGRES_PASSWORD',
        'It is generated by install.sh and passed through docker-compose.'
      ),
      max: POOL_MAX,
      statementTimeoutMs: STATEMENT_TIMEOUT_MS,
      idleInTransactionTimeoutMs: IDLE_IN_TRANSACTION_TIMEOUT_MS,
    },

    // Startup DT connection values. Removed in phase 4 when the connection
    // becomes per-user; retained here so phase 0 changes no behaviour.
    dt: {
      startupApiUrl: (env.DT_API_URL || 'http://localhost:8080').replace(/\/$/, ''),
      startupApiKey: (env.DT_API_KEY || '').replace(/[\x00-\x1F\x7F]/g, '').trim(),
    },
  };

  if (cfg.session.idleHours > cfg.session.absoluteHours) {
    throw new ConfigError(
      `SESSION_IDLE_HOURS (${cfg.session.idleHours}) cannot exceed ` +
      `SESSION_ABSOLUTE_HOURS (${cfg.session.absoluteHours}) — the idle window would never be reached`
    );
  }

  return Object.freeze(cfg);
}

/** Build the configuration from the real environment. */
function load(env = process.env) {
  return parseConfig(env);
}

module.exports = { parseConfig, load, ConfigError, DEFAULTS };
