// SPDX-License-Identifier: MIT
// Copyright (c) 2024 Dependency-Track Risk Dashboard contributors
'use strict';

// Report job registry, DT data collection and the report runner.
//
// Phase 6 moves the registry and the generated bytes into the database. Until
// then reportJobs is a process-global Map with no ownership dimension.

const fs   = require('fs');
const path = require('path');
const { log } = require('./log');
const { dtGetWithRetry } = require('./dt-fetch');
const { makeSemaphore } = require('./async-utils');
const { buildExcelReport } = require('./excel');

const REPORT_TIMEOUT_MS     = 30 * 60_000;  // 30 min hard limit per job
const FINDINGS_PAGE_SIZE    = 300;  // DT API page size for findings
const VIOLATIONS_PAGE_SIZE  = 300;  // DT API page size for violation queries
const VALID_RISK_TYPES      = new Set(['security', 'license', 'operational']);

// Injected at boot: { reportDir, reportRegistry, reportTmp,
//                     reportConcurrency, violationConcurrency, getEffectiveConfig }
let _deps = null;

function configure(d) { _deps = d; }

function deps() {
  if (!_deps) throw new Error('reports has not been configured — call configure() during boot');
  return _deps;
}

// ── Report job registry ───────────────────────────────────────────────────────
// In-memory Map; loaded from deps().reportRegistry on startup and saved atomically
// after every status transition.
//
// Job shape stored in registry file (cancelFlag is runtime-only, not persisted):
//   { id, status, filename, error, progress:{done,total}, createdAt, updatedAt }

const reportJobs = new Map(); // id → full job object (includes runtime cancelFlag)

function saveRegistry() {
  try {
    fs.mkdirSync(deps().reportDir, { recursive: true });
    const entries = [];
    for (const job of reportJobs.values()) {
      // Omit runtime-only fields before persisting
      const { cancelFlag, watchdogId, ...persisted } = job; // eslint-disable-line no-unused-vars
      entries.push(persisted);
    }
    fs.writeFileSync(deps().reportTmp, JSON.stringify(entries, null, 2), 'utf8');
    fs.renameSync(deps().reportTmp, deps().reportRegistry);
  } catch (e) {
    log('error', `Failed to save report registry: ${e.message}`);
  }
}

function loadRegistry() {
  try {
    if (!fs.existsSync(deps().reportRegistry)) return;
    const entries = JSON.parse(fs.readFileSync(deps().reportRegistry, 'utf8'));
    for (const entry of entries) {
      // Jobs that were 'running' when the service stopped cannot be resumed —
      // mark them failed so the user knows what happened.
      if (entry.status === 'running') {
        entry.status    = 'failed';
        entry.error     = 'Service restarted while this report was being generated.';
        entry.updatedAt = new Date().toISOString();
      }
      reportJobs.set(entry.id, { ...entry, cancelFlag: { cancelled: false } });
    }
    log('info', `Loaded ${reportJobs.size} report job(s) from registry`);
  } catch (e) {
    log('warn', `Could not load report registry (starting fresh): ${e.message}`);
  }
}

// ── Shared report data collector ─────────────────────────────────────────────
/**
 * Fetch security findings, license violations, and operational violations for
 * a list of projects.  Shared between runReportJob (registry-tracked) and
 * runScheduledJob (fire-and-email).
 *
 * @param {string}   apiUrl
 * @param {string}   apiKey
 * @param {Array}    projects    — [{ uuid, name, version }]
 * @param {string[]} riskTypes   — subset of ['security','license','operational']
 * @param {{ cancelled: boolean }} cancelFlag
 * @param {Function} [onProgress]  — called with (riskType) after each project finishes that category
 * @returns {Promise<object>} collected data maps
 */
async function collectReportData(apiUrl, apiKey, projects, riskTypes, cancelFlag, onProgress) {
  const semaphore     = makeSemaphore(deps().reportConcurrency);
  const violationSema = makeSemaphore(deps().violationConcurrency);

  const secFindings       = [];
  const secProjectSummary = new Map();
  const secComponentMap   = new Map();
  const licViolations     = [];
  const licProjectSummary = new Map();
  const opsViolations     = [];
  const opsProjectSummary = new Map();

  const tasks = projects.map(proj =>
    semaphore(async () => {
      if (cancelFlag.cancelled) return;

      await Promise.all([
        // ── Security findings ───────────────────────────────────────
        riskTypes.includes('security')
          ? (async () => {
              log('info', `[collect] Security findings for "${proj.name}" ${proj.version || ''}`);
              const findings = await fetchAllFindings(apiUrl, apiKey, proj.name, proj.version || '', cancelFlag);
              const sev = { critical: 0, high: 0, medium: 0, low: 0, unassigned: 0 };
              for (const f of findings) {
                secFindings.push(f);
                const s = (f.vulnerability?.severity || 'UNASSIGNED').toLowerCase();
                if (s in sev) sev[s]++; else sev.unassigned++;
                const c    = f.component || {};
                const cKey = [c.name, c.group].filter(Boolean).join('-');
                if (cKey) {
                  const entry = secComponentMap.get(cKey) || { count: 0, projects: new Set() };
                  entry.count++;
                  entry.projects.add(proj.name);
                  secComponentMap.set(cKey, entry);
                }
              }
              secProjectSummary.set(proj.uuid, { name: proj.name, version: proj.version, ...sev });
              if (onProgress) onProgress('security');
            })()
          : Promise.resolve(),

        // ── License violations ──────────────────────────────────────
        riskTypes.includes('license')
          ? violationSema(async () => {
              log('info', `[collect] License violations for "${proj.name}" ${proj.version || ''}`);
              const counts = { fail: 0, warn: 0, info: 0 };
              await streamViolationsForProject(apiUrl, apiKey, proj, 'license', cancelFlag, (v) => {
                const c   = v.component       || {};
                const pc  = v.policyCondition || {};
                const pol = pc.policy         || {};
                const state = (pol.violationState || 'INFO').toUpperCase();
                licViolations.push({
                  projName:    proj.name,
                  projVersion: proj.version || '',
                  component:   [c.name, c.group].filter(Boolean).join('-') || c.name || '',
                  compVersion: c.version                         || '',
                  licenseName: c.resolvedLicense?.name           || '',
                  licenseId:   c.resolvedLicense?.licenseId      || '',
                  license:     pc.value                          || '',
                  policy:      pol.name                          || '',
                  state,
                });
                const stLower = state.toLowerCase();
                if (stLower in counts) counts[stLower]++;
              });
              licProjectSummary.set(proj.uuid, { name: proj.name, version: proj.version, ...counts });
              if (onProgress) onProgress('license');
            })
          : Promise.resolve(),

        // ── Operational violations ──────────────────────────────────
        riskTypes.includes('operational')
          ? violationSema(async () => {
              log('info', `[collect] Operational violations for "${proj.name}" ${proj.version || ''}`);
              const counts = { fail: 0, warn: 0, info: 0 };
              await streamViolationsForProject(apiUrl, apiKey, proj, 'operational', cancelFlag, (v) => {
                const c   = v.component       || {};
                const pc  = v.policyCondition || {};
                const pol = pc.policy         || {};
                const state = (pol.violationState || 'INFO').toUpperCase();
                opsViolations.push({
                  projName:    proj.name,
                  projVersion: proj.version || '',
                  component:   [c.name, c.group].filter(Boolean).join('-') || c.name || '',
                  compVersion: c.version  || '',
                  policy:      pol.name   || '',
                  subject:     pc.subject || '',
                  condition:   pc.value   || '',
                  state,
                });
                const stLower = state.toLowerCase();
                if (stLower in counts) counts[stLower]++;
              });
              opsProjectSummary.set(proj.uuid, { name: proj.name, version: proj.version, ...counts });
              if (onProgress) onProgress('operational');
            })
          : Promise.resolve(),
      ]);
    })
  );

  await Promise.all(tasks);

  if (cancelFlag.cancelled) {
    throw Object.assign(new Error('__CANCELLED__'), { isCancelled: true });
  }

  return {
    secFindings, secProjectSummary, secComponentMap,
    licViolations, licProjectSummary,
    opsViolations, opsProjectSummary,
  };
}

// ── Findings fetch helper ─────────────────────────────────────────────────────
/**
 * Fetch all finding pages from DependencyTrack for one project.
 * Uses the text-search API:
 *   /api/v1/finding?textSearchInput={name}%20{version}&severity=...
 * Paginates until X-Total-Count is satisfied or a short page is returned.
 * Checks cancelFlag before every page request.
 */
async function fetchAllFindings(apiUrl, apiKey, name, version, cancelFlag) {
  const baseQs = [
    'showInactive=false',
    'showSuppressed=false',
    'textSearchField=vulnerability_id,vulnerability_title,component_name,component_version,project_name',
    `textSearchInput=${encodeURIComponent(`${name} ${version}`)}`,
    'severity=critical,high,medium,low,unassigned',
    'analysisStatus=NOT_SET,EXPLOITABLE,IN_TRIAGE',
    `pageSize=${FINDINGS_PAGE_SIZE}`,
  ].join('&');

  const all = [];
  let page = 1;
  while (true) {
    if (cancelFlag.cancelled) throw Object.assign(new Error('__CANCELLED__'), { isCancelled: true });
    const urlPath = `/api/v1/finding?${baseQs}&pageNumber=${page}`;
    log('info', `[report-fetch] GET ${apiUrl}${urlPath}`);
    const { json, headers } = await dtGetWithRetry(urlPath, apiUrl, apiKey);
    const batch = Array.isArray(json) ? json : [];
    all.push(...batch);
    const total = parseInt(headers['x-total-count'] || '0', 10);
    if ((total > 0 && all.length >= total) || batch.length < FINDINGS_PAGE_SIZE) break;
    page++;
  }
  return all;
}

// ── Per-project violation fetch helper ───────────────────────────────────────
/**
 * Stream all violation pages for one project and risk type, invoking onItem(v)
 * for each violation as it is received.  The raw DT objects are NOT accumulated
 * in an array — each page's objects are processed by the caller's callback and
 * then become eligible for GC before the next page is fetched.  This keeps
 * memory usage bounded to ~one page of raw objects at a time regardless of how
 * many total violations a project has.
 *
 * @param {Function} onItem  called synchronously for each violation object on a page
 * @returns {Promise<number>} total violation count processed
 */
async function streamViolationsForProject(apiUrl, apiKey, proj, riskType, cancelFlag, onItem) {
  const dtRiskType = riskType === 'license' ? 'LICENSE' : 'OPERATIONAL';
  // DT's project={uuid} filter is silently ignored on this version; instead use
  // project_name text search (same pattern as fetchAllFindings) and filter by
  // project UUID in-memory to exclude partial-name matches from other projects.
  const baseQs = [
    'showInactive=false',
    'suppressed=false',
    `riskType=${dtRiskType}`,
    'textSearchField=project_name',
    `textSearchInput=${encodeURIComponent(proj.name)}`,
    `pageSize=${VIOLATIONS_PAGE_SIZE}`,
  ].join('&');

  let processed = 0;
  let fetched   = 0;   // unfiltered count from API, used for pagination boundary
  let page = 1;
  while (true) {
    if (cancelFlag.cancelled) throw Object.assign(new Error('__CANCELLED__'), { isCancelled: true });
    const urlPath = `/api/v1/violation?${baseQs}&pageNumber=${page}`;
    log('info', `[report-fetch] GET ${apiUrl}${urlPath}`);
    const { json, headers } = await dtGetWithRetry(urlPath, apiUrl, apiKey);
    const batch = Array.isArray(json) ? json : (json?.violations || []);
    for (const v of batch) {
      // Only keep violations whose project UUID matches exactly — guards against
      // text-search returning partial-name matches from other projects.
      if (v.project?.uuid === proj.uuid) { onItem(v); processed++; }
    }
    fetched += batch.length;
    const total = parseInt(headers['x-total-count'] || '0', 10);
    if (batch.length < VIOLATIONS_PAGE_SIZE || (total > 0 && fetched >= total)) break;
    page++;
  }
  return processed;
}

// ── Report job runner ─────────────────────────────────────────────────────────
/**
 * Registry-tracked background job.  Delegates data collection to collectReportData
 * so the logic is shared with runScheduledJob.
 *
 * @param {string}   id        — job UUID
 * @param {Array}    projects  — [{ uuid, name, version }]
 * @param {string[]} riskTypes — subset of ['security','license','operational']
 */
async function runReportJob(id, projects, riskTypes) {
  const job = reportJobs.get(id);

  job.status    = 'running';
  job.riskTypes = riskTypes;
  // One progress counter per selected risk type so the UI shows an independent bar.
  job.progress  = Object.fromEntries(
    riskTypes.map(rt => [rt, { done: 0, total: projects.length }])
  );
  job.updatedAt = new Date().toISOString();
  saveRegistry();

  const watchdog = setTimeout(() => {
    log('warn', `Report job ${id} timed out after ${REPORT_TIMEOUT_MS / 60_000} min`);
    job.cancelFlag.cancelled = true;
    job.cancelReason = 'timeout';
  }, REPORT_TIMEOUT_MS);

  try {
    const { apiUrl, apiKey } = deps().getEffectiveConfig();
    if (!apiKey) throw new Error('DT_API_KEY is not configured on the cache service.');

    const reportData = await collectReportData(
      apiUrl, apiKey, projects, riskTypes, job.cancelFlag,
      (rt) => {
        job.progress[rt].done++;
        job.updatedAt = new Date().toISOString();
        saveRegistry();
      }
    );

    const ts       = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `vulnerability_report_${ts}.xlsx`;
    const filePath = path.join(deps().reportDir, filename);
    fs.mkdirSync(deps().reportDir, { recursive: true });

    const totalRows = reportData.secFindings.length + reportData.licViolations.length + reportData.opsViolations.length;
    log('info', `Report ${id}: building Excel (${totalRows} rows, types: ${riskTypes.join(',')})`);
    await buildExcelReport(filePath, { riskTypes, ...reportData });

    clearTimeout(watchdog);
    job.status    = 'completed';
    job.filename  = filename;
    job.filePath  = filePath;
    job.updatedAt = new Date().toISOString();
    log('info', `Report ${id}: completed — ${filename}`);

  } catch (err) {
    clearTimeout(watchdog);
    const isCancelled = err.isCancelled || job.cancelFlag.cancelled;
    job.status    = 'failed';
    job.error     = isCancelled
      ? (job.cancelReason === 'timeout'
          ? `Timed out after ${REPORT_TIMEOUT_MS / 60_000} minutes.`
          : 'Cancelled by user.')
      : err.message;
    job.updatedAt = new Date().toISOString();
    log('error', `Report ${id} failed: ${job.error}`);
  }

  saveRegistry();
}

/** Serialise a job for the API response (strip runtime-only fields). */
function jobToApi(job) {
  const { cancelFlag, watchdogId, filePath, ...pub } = job; // eslint-disable-line no-unused-vars
  return pub;
}

module.exports = {
  configure, reportJobs, saveRegistry, loadRegistry, jobToApi,
  collectReportData, fetchAllFindings, streamViolationsForProject, runReportJob,
  REPORT_TIMEOUT_MS, FINDINGS_PAGE_SIZE, VIOLATIONS_PAGE_SIZE, VALID_RISK_TYPES,
};
